import { Inter } from "next/font/google";
import TopBar from "../component/TopBar";



const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Hello chat app",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <TopBar/>
        {children}
        </body>
    </html>
  );
}
